# Generated by Django 5.1.4 on 2025-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='name',
            new_name='first',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='flights.flight'),
        ),
    ]
